### ISSUE TITLE
vaptcha/vaptcha-sdk 已经被废弃了

### ISSUE THREAD

**Issue by cornjosh** [tradzero/Vaptcha#1]
官方扩展不知道为什么已经被删掉了，可能要自己写一个完整的扩展了

**Comment by tradzero** [comment]
> 官方扩展不知道为什么已经被删掉了，可能要自己写一个完整的扩展了

那可能要靠你自己来弄了 我们自己都没在用vaptcha了2333

**Comment by cornjosh** [comment]
ok，感谢回复，有时间我再撸个扩展吧

**Comment by tradzero** [comment]
> ok，感谢回复，有时间我再撸个扩展吧

嗯 没事 我看他的api接口功能复杂度还行 然后看了一眼昨晚好像开了个项目 估计代码还没上传吧 如果那个项目有更新我可以考虑更新下这个包

**Comment by cornjosh** [comment]
嗯，看官方怎么搞了，小项目等不及先用 recaptcha ，等上线稳定以后再考虑换 vaptcha
（删SDK真是看不懂）
